// Generated by Wrangler by running `wrangler types`

interface Env {
	GOOGLE_GENERATIVE_AI_API_KEY: string;
	OPENAI_API_KEY: string;
	Chat: DurableObjectNamespace<import("./src/server").Chat>;
	DB: D1Database;
}
