name = "agent-test"
compatibility_date = "2025-02-04"
compatibility_flags = [ "nodejs_compat" ]
main = "src/server.ts"

assets = { directory = "./public/" }

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[durable_objects.bindings]]
name = "Chat"
class_name = "Chat"

  # { name = "AssistantAgent", class_name = "AssistantAgent" }
# ]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["Chat"]
